<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="iodine">
<xacro:property name="base_radius"    value="0.175" />
<xacro:property name="base_height"   value="0.08" />
<xacro:property name="wheel_separation" value="0.26" />
<xacro:property name="wheel_radius"     value="0.04" />
<xacro:property name="wheel_offset"     value="0.005" />
<xacro:property name="wheel_width"      value="0.02" />
<xacro:property name="sphere_radius"    value="0.01" />
<xacro:property name="lidar_radius"    value="0.035" />
<xacro:property name="lidar_height"   value="0.03" />
<xacro:property name="box_length"    value="0.02" />
<xacro:property name="box_width"   value="0.016" />
<xacro:property name="box_height"    value="0.08" />
<xacro:property name="footprint_z"      value="${base_height/2 + sphere_radius}" />
<xacro:property name="control_config"   value="$(find iodine_description)/config/diff_drive_control.yaml" />


    <!-- LINKS -->
    <link name="base_footprint"/>

    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_height}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="white">
                <color rgba="1 1 1 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${base_height}" radius="${base_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <mass value="4.2"/>
            <inertia ixx="0.0344" ixy="0.0" ixz="0.0" iyy="0.0344" iyz="0.0" izz="0.0643"/>
        </inertial>
    </link>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
            <origin rpy="1.5707 0 0" xyz="0 0 0"/>
            <material name="black">
                <color rgba="0 0 0 1.0"/>
            </material>
        </visual>


        <collision>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
            <origin rpy="1.5707 0 0" xyz="0 0 0"/>
        </collision>


        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0000433" ixy="0.0" ixz="0.0" iyy="0.0000433" iyz="0.0" izz="0.00008"/>
        </inertial>
    </link>
    
    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
            <origin rpy="1.5707 0 0" xyz="0 0 0"/>
            <material name="black">
                <color rgba="0 0 0 1.0"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length="${wheel_width}" radius="${wheel_radius}" />
            </geometry>
            <origin rpy="1.5707 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.1"/>
            <inertia ixx="0.0000433" ixy="0.0" ixz="0.0" iyy="0.0000433" iyz="0.0" izz="0.00008"/>
        </inertial>
    </link>

    <link name="front_ball_caster">
        <visual>
            <geometry>
                <sphere radius="${sphere_radius}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${sphere_radius}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.06"/>
            <inertia ixx="0.0000024" ixy="0.0" ixz="0.0" iyy="0.0000024" iyz="0.0" izz="0.0000024"/>
        </inertial>
    </link>


    <link name="back_ball_caster">
        <visual>
            <geometry>
                <sphere radius="${sphere_radius}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="blue">
                <color rgba="0.1 0.1 0.8 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <sphere radius="${sphere_radius}" />
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.06"/>
            <inertia ixx="0.0000024" ixy="0.0" ixz="0.0" iyy="0.0000024" iyz="0.0" izz="0.0000024"/>
        </inertial>
    </link>

    <link name="chassis_link">
    </link>

    <link name="imu_link">
    </link>

    <link name="lidar_link">
        <visual>
            <geometry>
                <cylinder length= "${lidar_height}" radius="${lidar_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
            <material name="yellow">
                <color rgba="1 1 0 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <cylinder length= "${lidar_height}" radius="${lidar_radius}"/>
            </geometry>
            <origin rpy="0 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.2"/>
            <inertia ixx="0.00007625" ixy="0.0" ixz="0.0" iyy="0.00007625" iyz="0.0" izz="0.0001225"/>
        </inertial>
    </link>

    <link name="depth_camera_link">
        <visual>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
            <material name="green">
                <color rgba="0 1 0 1"/>
            </material>
        </visual>

        <collision>
            <geometry>
                <box size="${box_length} ${box_width} ${box_height}"/>
            </geometry>
            <origin rpy="1.57 0 0" xyz="0 0 0"/>
        </collision>

        <inertial>
            <mass value="0.08"/>
            <inertia ixx="0.000044373" ixy="0.0" ixz="0.0" iyy="0.000045333" iyz="0.0" izz="0.0000043733"/>
        </inertial>
    </link>

    <!-- JOINTS -->
    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_footprint"/>
        <child link="base_link"/>
        <origin xyz="0 0 ${footprint_z}" rpy="0 0 0"/>
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -0.13 -0.005" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 0.13 -0.005" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
    </joint>


    <joint name="front_ball_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="front_ball_caster"/>
        <origin xyz="0.145 0.0 -0.035" rpy="0 0 0"/>
    </joint>

    <joint name="back_ball_caster_joint" type="fixed">
        <parent link="base_link"/>
        <child link="back_ball_caster"/>
        <origin xyz="-0.145 0.0 -0.035" rpy="0 0 0"/>
    </joint>

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis_link"/>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>

    <joint name="imu_joint" type="fixed">
        <parent link="base_link"/>
        <child link="imu_link"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <joint name="lidar_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_link"/>
        <origin xyz="0.075 0 0.055" rpy="0 0 0"/>
    </joint>

    <joint name="camera_joint" type="fixed">
        <parent link="base_link"/>
        <child link="depth_camera_link"/>
        <origin xyz="0.165 0 0" rpy="0 0 0"/>
    </joint>

    <!-- GAZEBO PLUGINS -->
    <!-- Differential Drive - https://gazebosim.org/api/gazebo/4.5/classignition_1_1gazebo_1_1systems_1_1DiffDrive.html [gazebosim.org] -->
    <gazebo>
        <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
            <left_joint>left_wheel_joint</left_joint>
            <right_joint>right_wheel_joint</right_joint>

            <!-- Kinematics -->
            <wheel_separation>${wheel_separation}</wheel_separation>
            <wheel_radius>${wheel_radius}</wheel_radius>

            <odom_publish_frequency>50</odom_publish_frequency>

            <!-- TF Frames -->
            <frame_id>/odom</frame_id>
            <child_frame_id>/base_footprint</child_frame_id>

            <!-- topics -->
            <topic>/model/iodine/cmd_vel</topic>
            <odom_topic>/model/iodine/odometry</odom_topic>
            <tf_topic>/model/iodine/tf</tf_topic>
        </plugin>
    </gazebo>

    <gazebo>
        <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher">
            <update_rate>50</update_rate>
            <joint_name>right_wheel_joint</joint_name>
            <joint_name>left_wheel_joint</joint_name>
        </plugin>
    </gazebo>

    <gazebo reference="right_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
    </gazebo>

    <gazebo reference="left_wheel">
        <mu1 value="1.0"/>
        <mu2 value="1.0"/>
    </gazebo>

    <gazebo reference="front_ball_caster">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="back_ball_caster">
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    <gazebo reference="lidar_link">
        <sensor type="gpu_lidar" name="lidar_sensor">
            <topic>/model/iodine/scan</topic>
            <frame_id>lidar_link</frame_id>
            <ignition_frame_id>lidar_link</ignition_frame_id>
            <update_rate>10.0</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>1024</samples>
                        <resolution>1</resolution>
                        <min_angle>-2.35619</min_angle>
                        <max_angle>2.35619</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.2</min>
                    <max>20.0</max>
                    <resolution>0.03</resolution>
                </range>
            </ray>
            <always_on>true</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <gazebo>
        <plugin filename="libignition-gazebo-sensors-system.so" name="ignition::gazebo::systems::Sensors">
            <render_engine>ogre2</render_engine>
        </plugin>
    </gazebo>

    <gazebo reference="depth_camera_link">
        <sensor type="depth" name="depth_camera_sensor">
            <update_rate>60.0</update_rate>
            <camera>
                <horizontal_fov>1.5184</horizontal_fov>
                <image>
                    <width>1280</width>
                    <height>720</height>
                    <format>R8G8B8</format>
                </image>
                <clip>
                    <near>0.3</near>
                    <far>4.0</far>
                </clip>
            </camera>
            <topic>/model/iodine/depth</topic>
            <frame_id>depth_camera_link</frame_id>
            <always_on>1</always_on>
            <visualize>true</visualize>
        </sensor>
    </gazebo>

    <gazebo reference="imu_link">
        <sensor type="imu" name="imu_sensor">
            <pose>0 0 0 0 0 0</pose>
            <update_rate>100.0</update_rate>
            <imu>
                <angular_velocity>
                    <x>0.0</x>
                    <y>0.0</y>
                    <z>0.0</z>
                </angular_velocity>
                <linear_acceleration>
                    <x>0.0</x>
                    <y>0.0</y>
                    <z>0.0</z>
                </linear_acceleration>
            </imu>
            <plugin filename="libignition-gazebo-imu-system.so" name="ignition::gazebo::systems::Imu">
                <topic>/model/iodine/imu</topic>
                <frame_id>imu_link</frame_id>
            </plugin>
        </sensor>
    </gazebo>
</robot>